This notebook is for turning overlap files made by bedtools intersect into a nicely formatted table

In [15]:
import os
import csv

root_dir = '.'


with open('overlap_table.csv', 'wb') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["seqA", "seqB", "numOverlap"] )
    for directory, subdirectories, files in os.walk(root_dir):
        for filename in files:
            if(str(filename).endswith('bam')):
                print filename

                a=filename[0:3]
                b=filename[4:7]
                print a
                print b

                num_lines = sum(1 for line in open(filename))
                print num_lines
                
                writer.writerow([a, b, num_lines]);

    writer.close()

JA1_JA2_overlap.bam
JA1
JA2
2958
JA1_JA3_overlap.bam
JA1
JA3
2958
JA1_JA4_overlap.bam
JA1
JA4
2958
JA1_JA5_overlap.bam
JA1
JA5
2958
JA1_JA6_overlap.bam
JA1
JA6
2958
JA1_JA7_overlap.bam
JA1
JA7
2958
JA1_JA8_overlap.bam
JA1
JA8
2958
JA2_JA3_overlap.bam
JA2
JA3
67254
JA2_JA4_overlap.bam
JA2
JA4
67254
JA2_JA5_overlap.bam
JA2
JA5
67254
JA2_JA6_overlap.bam
JA2
JA6
67254
JA2_JA7_overlap.bam
JA2
JA7
67254
JA2_JA8_overlap.bam
JA2
JA8
67254
JA3_JA4_overlap.bam
JA3
JA4
100383
JA3_JA5_overlap.bam
JA3
JA5
100383
JA3_JA6_overlap.bam
JA3
JA6
100383
JA3_JA7_overlap.bam
JA3
JA7
100383
JA3_JA8_overlap.bam
JA3
JA8
100383
JA4_JA5_overlap.bam
JA4
JA5
489224
JA4_JA6_overlap.bam
JA4
JA6
489224
JA4_JA7_overlap.bam
JA4
JA7
489224
JA4_JA8_overlap.bam
JA4
JA8
489224
JA5_JA6_overlap.bam
JA5
JA6
91261
JA5_JA7_overlap.bam
JA5
JA7
91261
JA5_JA8_overlap.bam
JA5
JA8
91261
JA6_JA7_overlap.bam
JA6
JA7
191100
JA6_JA8_overlap.bam
JA6
JA8
191100
JA7_JA8_overlap.bam
JA7
JA8
35794

AttributeError: '_csv.writer' object has no attribute 'close'

In [16]:
import pandas as pd

table = pd.read_csv('overlap_table.csv')
table

   seqA seqB  numOverlap
0   JA1  JA2        2958
1   JA1  JA3        2958
2   JA1  JA4        2958
3   JA1  JA5        2958
4   JA1  JA6        2958
5   JA1  JA7        2958
6   JA1  JA8        2958
7   JA2  JA3       67254
8   JA2  JA4       67254
9   JA2  JA5       67254
10  JA2  JA6       67254
11  JA2  JA7       67254
12  JA2  JA8       67254
13  JA3  JA4      100383
14  JA3  JA5      100383
15  JA3  JA6      100383
16  JA3  JA7      100383
17  JA3  JA8      100383
18  JA4  JA5      489224
19  JA4  JA6      489224
20  JA4  JA7      489224
21  JA4  JA8      489224
22  JA5  JA6       91261
23  JA5  JA7       91261
24  JA5  JA8       91261
25  JA6  JA7      191100
26  JA6  JA8      191100
27  JA7  JA8       35794

# Categorizing peaks

In [1]:
# Read in merged peaks file
import pandas as pd

merged_peaks = pd.read_table("/Volumes/oncogxA/Projects/CHENCS/Olivier/bed/all.merged.bed", header = None, sep="\t")
merged_peaks.columns = ["chrom", "start", "end", "exps"]
merged_peaks_og = merged_peaks
merged_peaks

       chrom     start       end                 exps
0       chr1     10166     10341              JA5;JA8
1       chr1     10420     10605              JA4;JA6
2       chr1     12993     13150                  JA4
3       chr1     14849     15014                  JA6
4       chr1     16378     16535                  JA4
5       chr1     16716     16880              JA4;JA8
6       chr1     17403     17568              JA6;JA4
7       chr1     20053     20210                  JA4
8       chr1     79351     79508                  JA4
9       chr1     87111     87268                  JA4
10      chr1     88144     88285                  JA2
11      chr1     88696     88876              JA6;JA4
12      chr1     89794     89951                  JA4
13      chr1    128622    128779                  JA4
14      chr1    135098    135280              JA6;JA4
15      chr1    136725    136968              JA6;JA4
16      chr1    138922    139079                  JA4
17      chr1    235040    235197                  JA4
18      chr1    235592    235749                  JA4
19      chr1    523708    523865                  JA4
20      chr1    532907    533064                  JA4
21      chr1    534082    534316              JA6;JA4
22      chr1    538649    538806                  JA4
23      chr1    540797    540954                  JA4
24      chr1    546150    546328              JA6;JA5
25      chr1    662496    662661                  JA6
26      chr1    714061    714357              JA4;JA2
27      chr1    714475    714642                  JA7
28      chr1    716060    716217                  JA4
29      chr1    721418    721575                  JA4
...      ...       ...       ...                  ...
894492  chrY  58972975  58973136              JA3;JA2
894493  chrY  58975462  58975603                  JA2
894494  chrY  58978343  58978484                  JA2
894495  chrY  58984605  58984774              JA4;JA2
894496  chrY  58986048  58986209                  JA3
894497  chrY  58989769  58989910                  JA2
894498  chrY  58992216  58992357                  JA2
894499  chrY  58993245  58993420              JA5;JA4
894500  chrY  58993871  58994046                  JA5
894501  chrY  59001516  59001679                  JA8
894502  chrY  59001907  59002161              JA2;JA4
894503  chrY  59004644  59004809                  JA6
894504  chrY  59004924  59005087                  JA8
894505  chrY  59009640  59009801                  JA3
894506  chrY  59012915  59013080                  JA6
894507  chrY  59013672  59013847                  JA5
894508  chrY  59015024  59015199                  JA5
894509  chrY  59016249  59016410                  JA3
894510  chrY  59016868  59017254  JA5;JA3;JA2;JA6;JA8
894511  chrY  59018287  59018450                  JA8
894512  chrY  59019197  59019338                  JA2
894513  chrY  59022641  59022802                  JA3
894514  chrY  59022901  59023042                  JA2
894515  chrY  59026618  59026759                  JA2
894516  chrY  59027611  59027788              JA4;JA2
894517  chrY  59030063  59030228                  JA6
894518  chrY  59031650  59031807                  JA4
894519  chrY  59032521  59032678                  JA4
894520  chrY  59032689  59032864                  JA5
894521  chrY  59032871  59032990                  JA8

[894522 rows x 4 columns]

In [5]:
"""
Categories
1) Shared with everything
2) Shared with either vehicle
3) Shared between treatments
	2 & 3 & 5 & 6
4) Shared between target, same treatment 
	2 & 5
	3 & 6
5) Target and Treatment specific 
	just 2
	just 5
	just 3
	just 6
"""
# Shared between everything
everything = merged_peaks.ix[merged_peaks["exps"].str.contains("JA1") & merged_peaks["exps"].str.contains("JA2") & merged_peaks["exps"].str.contains("JA3") & merged_peaks["exps"].str.contains("JA4") & merged_peaks["exps"].str.contains("JA5") & merged_peaks["exps"].str.contains("JA6")]
merged_peaks = merged_peaks.ix[not merged_peaks["exps"].str.contains("JA1") and  not merged_peaks["exps"].str.contains("JA2")]

#merged_peaks = merged_peaks.drop(merged_peaks.ix[merged_peaks["exps"].str.contains("JA1") & merged_peaks["exps"].str.contains("JA2") & merged_peaks["exps"].str.contains("JA3") & merged_peaks["exps"].str.contains("JA4") & merged_peaks["exps"].str.contains("JA5") & merged_peaks["exps"].str.contains("JA6")])

# Shared with either vehicle
#in_vehicle = merged_peaks.ix[merged_peaks["exps"].str.contains("JA1") | merged_peaks["exps"].str.contains("JA4")]
print merged_peaks_og.size
print merged_peaks.size
print everything.size

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().